### ISSUE TITLE
Define latitude and longitude as DECIMAL

### ISSUE THREAD

**Issue by peterbenke** [FriendsOfTYPO3/tt_address#20] opened 2016-10-07 09:35 UTC
Hi,

latitude and longitude should be defined as DECIMAL in MySQL.
MySQL does not work properly with lomg numbers defined as FLOAT.

At last this ends in an error-message in TYPO3-Backend:
"These fields of record *** in table "tt_address" have not been saved correctly: latitude, longitude! The values might have changed due to type casting of the database."

(So long as latitude and longitude are shown in the backend by TCA ;-)).

Thank you!

**Comment by BastianBalthasarBux** [comment] 2016-10-26 14:49
Resolved with release 3.1.0
Although I want to mention, that the error was not (solely) caused by the DB datatype. ;)

**Closed** 2016-10-27 10:13 UTC
