### ISSUE TITLE
Class 'FriendsOfTYPO3\TtAddress\Domain\Model\Dto\Settings' not found

### ISSUE THREAD

**Issue by blueamerican** [FriendsOfTYPO3/tt_address#232] opened 2019-07-13 20:43 UTC
## Bug Report

when updateing tt_address from 3.24 to 4.30 i get the error in BE and FE:

Class 'FriendsOfTYPO3\TtAddress\Domain\Model\Dto\Settings' not found

I really wonder why i find no issue here.
Removing tt_address from PackageStates.php doesn't remove the error. 

**Environment**
- TYPO3 version(s): 8.7.19
- tt_address version: 4.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- server: jweiland php 7.2, mittwald php 7.1

**Comment by blueamerican** [comment] 2019-07-13 20:48
the same with 4.1.0

**Comment by blueamerican** [comment] 2019-07-13 20:58
related:
https://github.com/FriendsOfTYPO3/tt_address/issues/197

**Comment by Teisi** [comment] 2019-07-14 00:39
Workaround: deactivate the extension before update.
If you have allready this error, you have to deactivate the extension via Install-Tool.
After update, its recommended to use "dump autoload - Rebuild PHP Autoload Information" then activate the extension again.

**Comment by blueamerican** [comment] 2019-07-14 04:29
This is really annoying, sorry.
I do not understand this.

Where can i deactivate the extension in the install tool?
Where can i execute "dump autoload", if i do not use composer.

Or ist it true, that the extension cannot be updated without composer?
It is new for me, that i MUST use composer.

**Comment by crealistiques** [comment] 2019-07-22 08:03
@blueamerican 

Clearing the cache in the install tool as advised for me was not possible until I rebuild the composer autoload information. You can rebuild composer autoload information by clicking the button "Create autoload information for extensions" in the section "Dump autoload information" on the install tool startpage.

In case you can not access the install tool via the backend module please use the standalone install tool at yourdomain.com/typo3/install.

**Comment by BastianBalthasarBux** [comment] 2019-08-10 15:57
This is a duplicate of #197 so I close this one.

**Closed by BastianBalthasarBux** 2019-08-10 15:57 UTC
Labels: duplicate
