### ISSUE TITLE
Custom sorting don't work. After update from 5.1.2 -> 5.2.0

### ISSUE THREAD

**Issue by olegkarun** [FriendsOfTYPO3/tt_address#313] opened 2020-10-29 10:13 UTC
## Bug Report

**Current Behavior**
FlexForm settings `settings.sortBy` and  `settings.sortOrder` have no effect to list display

**Expected behavior/output**
`settings.sortBy = sorting` should show List view in sorting order.

**Environment**
- TYPO3 version(s): [9.5.22]
- tt_address version: [5.2.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]
- OS: [Linux 4.15.0-23-generic,  7.2.24-0ubuntu0.18.04.3]

**Possible Solution**
Problem in TypoScript `overrideFlexformSettingsIfEmpty` if remove plugin.tx_ttaddress.settings.sortBy from TypoScript FlexForm works againe.

**Additional context**
If setup with TypoScript all work
`plugin.tx_ttaddress.settings.sortBy = sorting`
But with FlexForm no. Same `sortOrder` but others like `categories` work with FlexForm

PS. For me also don't work

tt_address\Classes\Controller\AddressController.php ~ line 99
```
        // get the whole typoscript (_FRAMEWORK does not work anymore, don't know why)
        $tsSettings = $this->configurationManager->getConfiguration(
            ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT,
            'tx_ttaddress',
            'ttaddress_listview'
        ); 
```

**Comment by Patta** [comment] 2020-10-29 21:51
Should be already fixed in master. #308

**Comment by BastianBalthasarBux** [comment] 2020-11-19 21:59
Duplicate of: #308 
Already fixed in master.

**Closed by BastianBalthasarBux** 2020-11-19 21:59 UTC
Labels: bug, confirmed, duplicate
